### ISSUE TITLE
Question: Why have extension.js?

### ISSUE THREAD

**Issue by JamyGolden** [Base24/base24-vscode#12]
Hello @FredHappyface :)

I've just created a vscode extension for [base16-vscode](https://github.com/tinted-theming/base16-vscode). I started out with an extionson.js, but ended up dropping it and just having a "theme" extension. Is there a reason you didn't do this in this repo?

**Comment by FredHappyface** [comment]
Hey mine was based on the old base16 theme iirc however I do think the base 24 extension is in desperate need of a refresh so going to make that this months mission

**Comment by JamyGolden** [comment]
Ah ok I see. I ask because I just created a theme extension: https://github.com/tinted-theming/base16-vscode/pull/7 and I noticed that there isn’t a need to have any JavaScript running (extension.js) as long as the themes are registered in package.json and linked to the json theme. 

If you want to move any of your template repos to tinted theming I’d be happy to help maintain (no pressure though, I could still submit PRs in your org). I like base24 and want to make it a first-class citizen in tinted-theming.

**Comment by FredHappyface** [comment]
Oh awesome thank you very much for that! I'd be quite keen on moving a bunch of the template repos over so shall look at that over the next few weeks. In the meantime I've updated the base24 builder and the repo to behave more like the base16 vscode counterpart. Down the line I would like to update the template too as it is based on quite an old vscode theme now I think

**Comment by JamyGolden** [comment]
Cool! Not a big issue since the themes work in vscode now, but I noticed the ./themes/* files end with a double dot json `..json` so the theme names in vscode end with a dot, eg `base24-one-dark.`

**Comment by FredHappyface** [comment]
Oh good spot! Thank you I'll check that out!
