### ISSUE TITLE
Bug: Can't activate a theme

### ISSUE THREAD

**Issue by JamyGolden** [Base24/base24-vscode#13]
### Before you begin

- [x] I have checked for similar issues in the project's issue tracker.
- [x] I have searched closed issues to see if a similar problem was reported
  before.

### Description

1. I install the extension successfully
2. Set the theme to `base24` successfully
3. Open the `Base24 Activate Theme` list which lists all the themes
4. Selecting a theme asks me to restart VSCode
5. After restarting the theme isn't set

### Expected Behavior

After selecting the theme, it successfully sets the theme.

### Actual Behavior

No change after selecting the theme.

## System Information

Please provide the following additional information about your system or
environment:

- Operating System (OS):
- OS Version: Pop!OS (Linux)
- Installation type: Tried flatpak and `apt`

**Comment by FredHappyface** [comment]
Hopefully solved in the 0.3.0 release I've just published :)

**Comment by JamyGolden** [comment]
Nice! fixed for me :smile:
