### ISSUE TITLE
Question: Join us on Matrix?

### ISSUE THREAD

**Issue by JamyGolden** [Base24/base24-vscode#14]
I'm not sure if you know about it, but we moved off of IRC and are on https://matrix.to/#/#tinted-theming:matrix.org for IM type of chats. There aren't many of us there :sweat_smile: but it would be good to have you there so you can be part of random discussions that might happen.

Also not related to base* things, but I have a project idea I want to get your thoughts on (if you're ok with that) so would be good to have a place where I could send a DM :relaxed:

**Comment by FredHappyface** [comment]
Yeah sounds like a good idea actually, I had an account a while back though never used it so it since got binned. Happy to do a round 2 though :)

**Comment by JamyGolden** [comment]
I'm about done with a sublime-text template, in my mind it's going to be `github.com/tinted-theming/base16-sublime-text`, however, I'm starting to wonder if it may be better to group the different systems into 1. So `github.com/tinted-theming/sublime-text` could generate base16 and base24 templates for people to choose from. Maybe there are down sides I'm not thinking of though, what do you think?

**Comment by FredHappyface** [comment]
Yeah personally I'm happy with that. The point of base24 in the first place was to be forwards and backwards compatible to a good degree. So you could easily keep using base16 themes and schemes

**Comment by JamyGolden** [comment]
What do you think about including other systems? (Ones that may not exist yet). So where it works, especially for editor extensions, having “global templates” which allow users to select between any theme in the various systems. This would also mean that there would be multiple mustache templates in one of these repos.
